<?php

namespace AppBundle\Repository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQueryBirds($query)
    {
        return $this->createQueryBuilder('b')
            ->where('b.nom LIKE :query')
            ->setParameter('query', $query.'%')
            ->getQuery()
            ->getArrayResult()
            ;
    }

    
}
